---
abstract: 'A glimpse at an Enlightened Perl (module development tools).'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Kensho-ModuleDev
no_index:
  directory:
    - inc
    - t
requires:
  CPAN::Uploader: 0
  Carp::Always: 0
  Devel::NYTProf: 0
  Dist::Zilla: 0
  Modern::Perl: 0
  Module::Install: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Perl::Version: 0
  Pod::Readme: 0
  Software::License: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.28
